# Module: mysql
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.x/metricbeat-module-mysql.html

- module: mysql
  metricsets:
    - status
    - galera_status
    - performance
    #- query
  period: 10s

  hosts: ["${MYSQL_MONITORING_USERNAME}:${MYSQL_MONITORING_PASSWORD:}@tcp(${MY_SQL})/"]
